### ISSUE TITLE
Fatal errors should be 'fatal'?

### ISSUE THREAD

**Issue by nikolaposa** [wecodein/error-handling#3]
Default error handling implementation (`WeCodeIn\ErrorHandling\Handler\ErrorHandler`) is non-blocking by default, meaning that program execution won't be stopped. But I believe that `E_ERROR | E_PARSE | E_CORE_ERROR | E_COMPILE_ERROR | E_USER_ERROR` errors should be handled in a blocking way, as it does not make sense to continue the execution when they happen.

What do you think?

**Comment by dusanvejin** [comment]
@nikolaposa 

`E_ERROR` and `E_PARSE` errors are reported trough standard PHP exception handler, while`E_CORE_ERROR` and `E_COMPILE_ERROR` are handled on script shutdown, so in those cases termination is in progress.
Regarding `E_USER_ERROR ` I believe termination behavior can be added to `WeCodeIn\ErrorHandling\Handler\ErrorHandler`, I will work on that.

**Comment by dusanvejin** [comment]
@nikolaposa 

I introduced new error handler `WeCodeIn\ErrorHandling\Handler\BlockingErrorHandler`, [here](https://github.com/wecodein/error-handling/blob/master/examples/blocking-error-handler.php) you can see an example.
